site_name: Boden X-platform Framework

theme:
  name: 'material'
  palette:
    primary: 'White'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/AshampooSystems'
    - type: 'twitter'
      link: 'https://twitter.com/bodenhq'

repo_url: 'https://github.com/AshampooSystems/boden'
repo_name: 'boden'


markdown_extensions:
  - pymdownx.superfences
  - pymdownx.snippets:
      base_path: 'docs'
  - admonition
  - meta
  - codehilite
  - toc:
      permalink: true

nav:
  - Getting Started: 'getting-started.md'
  - Setup: 'setup.md'
  - Reference:
    - Foundation:
      - Base: 'reference/foundation/base.md'
      - String: 'reference/foundation/string.md'
      - Android:
        - Java:
          - Wrapping Java: 'reference/foundation/android/java/wrap-java-class.md'
    - Layout:
      - Summary: 'reference/layout/summary.md'
      - Layout: 'reference/layout/layout.md'
      - Stylesheet: 'reference/layout/stylesheet.md'
      - Yoga:
        - Summary: 'reference/layout/yoga/summary.md'
        - Stylesheet: 'reference/layout/yoga/stylesheet.md'
        - Json Stylesheet: 'reference/layout/yoga/json.md'
    - UI:
      - View: 'reference/ui/view.md'
      - Button: 'reference/ui/button.md'
      - TextField: 'reference/ui/text_field.md'
      - Stack: 'reference/ui/stack.md'
      - ViewCore: 'reference/ui/view_core.md'