site_name: Boden X-platform Framework

theme:
  name: 'material'
  palette:
    primary: 'white'

markdown_extensions:
  - codehilite

nav:
  - Getting Started: 'getting-started.md'
  - Setup: 'setup.md'
  - Reference:
    - Foundation:
      - Base: 'reference/foundation/base.md'
      - String: 'reference/foundation/string.md'
    - Layout:
      - Summary: 'reference/layout/summary.md'
      - Layout: 'reference/layout/layout.md'
      - Stylesheet: 'reference/layout/stylesheet.md'
      - Yoga:
        - Summary: 'reference/layout/yoga/summary.md'
        - Stylesheet: 'reference/layout/yoga/stylesheet.md'
        - Json Stylesheet: 'reference/layout/yoga/json.md'
    - UI:
      - View: 'reference/ui/view.md'
      - Button: 'reference/ui/button.md'
      - TextField: 'reference/ui/text_field.md'
      - ViewCore: 'reference/ui/view_core.md'