site_name: Boden Cross-Platform Framework

theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'White'
  feature:
    tabs: true
  logo: 'boden-logo-header.svg'
  favicon: 'favicon-32x32.png'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/AshampooSystems'
    - type: 'twitter'
      link: 'https://twitter.com/bodenhq'

repo_url: 'https://github.com/AshampooSystems/boden'
repo_name: 'boden'

extra_css:
  - 'stylesheets/cookieconsent.min.css'
  - 'stylesheets/boden.css'

extra_javascript:
  - 'javascripts/cookieconsent.min.js'

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      base_path: 'docs'
  - admonition
  - meta
  - codehilite
  - toc:
      permalink: true
  - markdown_include.include:
        base_path: docs

nav:
  - Getting Started:
    - getting-started/index.md
    - getting-started/first_app.md
    - Building Boden:
      - getting-started/building/mac.md
      - getting-started/building/windows.md
      - getting-started/building/linux.md
    - Installing Dependencies:
      - getting-started/installing_dependencies/mac.md
      - getting-started/installing_dependencies/windows.md
      - getting-started/installing_dependencies/linux.md
    - getting-started/troubleshooting/index.md
    - getting-started/faq.md
  - Guides:
    - guides/index.md
    - Fundamentals:
      - guides/fundamentals/properties.md
      - guides/fundamentals/resources.md
    - Layout:
      - guides/layout/summary.md
      - guides/layout/json.md
      - guides/layout/yoga.md
    - Extending Boden:
      - guides/extending/writing_view.md
      - guides/extending/writing_view_modules.md
      - guides/extending/wrap_java_class.md      
  - API Reference:
    - API Reference Overview: 'reference/index.md'
    - Foundation:
      - reference/foundation/application.md
      - reference/foundation/application_controller.md
      - reference/foundation/dispatch_queue.md
      - reference/foundation/notifier.md
      - reference/foundation/point.md
      - reference/foundation/property.md
      - reference/foundation/rect.md
      - reference/foundation/size.md
      - reference/foundation/streaming.md
      - reference/foundation/string.md
      - reference/foundation/transform.md
    - UI:
      - reference/ui/button.md
      - reference/ui/checkbox.md
      - reference/ui/click_event.md
      - reference/ui/container_view.md
      - reference/ui/image_view.md
      - reference/ui/label.md
      - reference/ui/layout.md
      - reference/ui/list_view.md
      - reference/ui/list_view_data_source.md
      - reference/ui/navigation_view.md
      - reference/ui/scroll_view.md
      - reference/ui/slider.md
      - reference/ui/styler.md
      - reference/ui/submit_event.md
      - reference/ui/switch.md
      - reference/ui/text_field.md
      - reference/ui/tri_state.md
      - reference/ui/view.md
      - reference/ui/view_core.md
      - reference/ui/view_core_factory.md
      - reference/ui/view_event.md
      - reference/ui/web_view.md
      - reference/ui/window.md
      - iOS:
        - reference/ui/ios/view_core.md
    - Net:
      - reference/net/http.md
      - reference/net/http_request.md
      - reference/net/http_response.md
    - Extra Modules:
      - Lottie:
        - reference/extra-modules/lottie/lottie_view.md
      - Yoga Layout:
        - reference/extra-modules/yoga/layout.md
  - Legal:
    - Legal: 'https://www.ashampoo-systems.com/base/about'
    - legal/privacy_policy.md
    - Licensing: 
      - Overview: 'legal/licensing/index.md'
      - FDL 1.3: 'legal/licensing/fdl-1.3.md'
      - GPL 2: 'legal/licensing/gpl-2.md'
      - GPL 3: 'legal/licensing/gpl-3.md'

google_analytics:
  - 'GTM-MP93ZKM'
  - 'auto'

copyright: 'Copyright &copy; 2019 Ashampoo Systems GmbH & Co. KG'
site_description: 'Boden is the new cross-platform framework for building real native mobile apps using native widgets and modern C++17. Boden is free and open source.'