site_name: Boden Cross-Platform Framework

theme:
  name: 'material'
  custom_dir: 'theme'
  palette:
    primary: 'White'
  feature:
    tabs: true
  logo: 'boden-logo-header-dark.png'
extra:
  social:
    - type: 'github'
      link: 'https://github.com/AshampooSystems'
    - type: 'twitter'
      link: 'https://twitter.com/bodenhq'

repo_url: 'https://github.com/AshampooSystems/boden'
repo_name: 'boden'

extra_css:
  - 'stylesheets/cookieconsent.min.css'
  - 'stylesheets/boden.css'

extra_javascript:
  - 'javascripts/cookieconsent.min.js'

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.details
  - pymdownx.snippets:
      base_path: 'docs'
  - admonition
  - meta
  - codehilite
  - toc:
      permalink: true
  - markdown_include.include:
        base_path: docs

nav:
  - Getting Started:
    - getting-started/index.md
    - Setup:
      - getting-started/setup/mac.md
      - getting-started/setup/win.md
      - getting-started/setup/linux.md
    - getting-started/first_app.md
    - Dependencies:
      - getting-started/dependency_installation/mac.md
      - getting-started/dependency_installation/win.md
      - getting-started/dependency_installation/linux.md
    - getting-started/troubleshooting/index.md
  - Guides:
    - Foundation:
      - guides/foundation/properties.md
    - Layout:
      - guides/layout/summary.md
      - guides/layout/json.md
      - Yoga:
        - guides/layout/yoga/summary.md
    - UI:
      - guides/ui/writing_view.md
      - guides/ui/writing_view_modules.md
  - API Reference:
    - Overview: 'reference/index.md'
    - Foundation:
      - reference/foundation/application.md
      - reference/foundation/application_controller.md
      - reference/foundation/base.md
      - reference/foundation/dispatch_queue.md
      - reference/foundation/notifier.md
      - reference/foundation/size.md
      - reference/foundation/string.md
      - reference/foundation/weak_callback.md
      - Properties:
        - reference/foundation/property/compare.md
        - reference/foundation/property/property.md
        - reference/foundation/property/streaming.md
        - reference/foundation/property/transform.md
      - Android:
        - Java:
          - reference/foundation/android/java/wrap-java-class.md
          - reference/foundation/android/java/jtobject.md
          - reference/foundation/android/java/method.md
          - reference/foundation/android/java/object.md
    - Layout:
      - reference/layout/flex_stylesheet.md
      - reference/layout/layout.md
      - reference/layout/layout_stylesheet.md
      - Yoga Layout:
        - reference/layout/yogalayout/layout.md
    - UI:
      - reference/ui/button.md
      - reference/ui/checkbox.md
      - reference/ui/click_event.md
      - reference/ui/container_view.md
      - reference/ui/fixed_view.md
      - reference/ui/image_view.md
      - reference/ui/label.md
      - reference/ui/list_view.md
      - reference/ui/list_view_data_source.md
      - reference/ui/navigation_view.md
      - reference/ui/scroll_view.md
      - reference/ui/text_field.md
      - reference/ui/tri_state.md
      - reference/ui/view.md
      - reference/ui/view_core_factory.md
      - reference/ui/view_event.md
      - reference/ui/window.md
      - Cores:
        - reference/ui/cores/view_core.md
        - IOS:
          - reference/ui/cores/ios/view_core.md
  - Legal:
    - Legal: 'https://www.ashampoo-systems.com/base/about'
    - legal/privacy_policy.md
    - Licensing: 
      - Overview: 'legal/licensing/index.md'
      - FDL 1.3: 'legal/licensing/fdl-1.3.md'
      - GPL 2: 'legal/licensing/gpl-2.md'
      - GPL 3: 'legal/licensing/gpl-3.md'
      - LGPL 2.1: 'legal/licensing/lgpl-2.1.md'
      - LGPL 3: 'legal/licensing/lgpl-3.md'

google_analytics:
  - 'UA-137911052-1'
  - 'auto'

copyright: 'Copyright &copy; 2019 Ashampoo Systems GmbH & Co. KG'